/* ShiftFit Settings v2 — functional preferences, privacy, account, support and legal screens. */
(function(){
  "use strict";
  const MODAL="shiftfit-settings-split-modal";
  const STORE="shiftfitSettings";
  function raw(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f;}catch(_){return f;}}
  function put(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch(_){return false;}}
  function settings(){return Object.assign({notifications:true,mealReminders:true,workoutReminders:true,waterReminders:false,appearance:"dark",units:"metric",weekStarts:"monday"},raw(STORE,{}));}
  function saveSettings(v){put(STORE,v);try{window.dispatchEvent(new CustomEvent("shiftfitSettingsChanged",{detail:v}));}catch(_){};applySettings(v);}
  function close(){const m=document.getElementById(MODAL);if(m)m.classList.remove("open");}
  function applySettings(v){document.documentElement.dataset.shiftfitAppearance=v.appearance||"dark";document.documentElement.dataset.shiftfitUnits=v.units||"metric";}
  function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");}
  function styles(){if(document.getElementById("shiftfit-settings-v2-style"))return;const s=document.createElement("style");s.id="shiftfit-settings-v2-style";s.textContent=`
#${MODAL}{position:fixed;inset:0;z-index:99995;display:none;align-items:flex-end;justify-content:center;background:rgba(0,0,0,.78)}#${MODAL}.open{display:flex}#${MODAL} .sheet{width:min(500px,100%);height:100dvh;overflow:auto;background:linear-gradient(180deg,#08091a,#050711);padding:24px 18px calc(110px + env(safe-area-inset-bottom));box-sizing:border-box;color:#fff}#${MODAL} .top{display:grid;grid-template-columns:48px 1fr 48px;align-items:center;margin-bottom:18px}.back{width:48px;height:48px;border-radius:50%;border:1px solid #303a60;background:#14182b;color:#fff;font-size:30px}.logo{text-align:center;font-size:26px;font-weight:1000;font-style:italic;letter-spacing:-2px}.bolt{color:#ff9d22}.fit{color:#8656ff}.subtitle{margin:5px 4px 20px;color:#aab1c5;font-size:14px;line-height:1.45}.group{margin:14px 0;padding:16px;border:1px solid #293253;border-radius:21px;background:linear-gradient(145deg,#11182d,#0b1020)}.group h3{margin:0 0 8px;color:#c5b5ff;font-size:13px;letter-spacing:1.4px}.item{width:100%;display:grid;grid-template-columns:46px minmax(0,1fr) 28px;gap:12px;align-items:center;padding:13px 0;border:0;border-top:1px solid rgba(255,255,255,.07);background:none;color:#fff;text-align:left}.item:first-of-type{border-top:0}.icon{width:46px;height:46px;border-radius:14px;display:grid;place-items:center;font-size:22px;background:rgba(139,92,246,.16)}.title{display:block;font-size:16px;font-weight:900}.copy{display:block;margin-top:3px;color:#aab1c5;font-size:11px;line-height:1.35}.value{display:block;margin-top:4px;color:#747e98;font-size:10px;font-weight:800}.arrow{color:#b39cff;font-size:27px;text-align:right}.backrow{display:flex;gap:10px;align-items:center;margin-bottom:20px}.backrow h1{margin:0;font-size:30px}.field{width:100%;padding:14px;border:1px solid #354267;border-radius:13px;background:#0b1021;color:#fff;font-size:15px;box-sizing:border-box}.label{display:block;margin:14px 0 7px;color:#bfc6da;font-size:12px;font-weight:800}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.save{width:100%;margin-top:16px;padding:16px;border:0;border-radius:15px;background:linear-gradient(135deg,#8b3cff,#5123c5);color:#fff;font-weight:950}.secondary{width:100%;margin-top:9px;padding:13px;border:1px solid #39466f;border-radius:14px;background:#11182d;color:#d7d1ff;font-weight:850}.check{display:flex;align-items:center;gap:10px;padding:13px 0;color:#e0e4ef;font-size:14px}.check input{width:19px;height:19px}.note{margin-top:12px;color:#7f879c;font-size:11px;line-height:1.5}.danger{border-color:#633344;color:#ffb7c5}.legal{color:#c9cfe0;font-size:13px;line-height:1.65}.legal h2{font-size:17px;color:#fff;margin:18px 0 7px}.toast{position:fixed;left:18px;right:18px;bottom:24px;z-index:100005;padding:13px 15px;border-radius:13px;background:#151b31;border:1px solid #39466f;color:#fff;text-align:center;font-size:13px;font-weight:800}
`;document.head.appendChild(s);}
  function shell(title,sub,body){const m=document.getElementById(MODAL);m.innerHTML=`<div class="sheet"><div class="top"><button class="back" type="button">‹</button><div class="logo"><span class="bolt">⚡</span><span>SHIFT</span><span class="fit">FIT</span></div><div></div></div><div class="backrow"><h1>${esc(title)}</h1></div><div class="subtitle">${sub}</div>${body}</div>`;m.classList.add("open");m.querySelector(".back").onclick=renderHome;m.onclick=e=>{if(e.target===m)close();};return m;}
  function toast(text){const old=document.querySelector(".toast");if(old)old.remove();const t=document.createElement("div");t.className="toast";t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2200);}
  function renderHome(){const m=document.getElementById(MODAL);if(!m)return;const v=settings();m.innerHTML=`<div class="sheet"><div class="top"><button class="back" type="button" aria-label="Close settings">‹</button><div class="logo"><span class="bolt">⚡</span><span>SHIFT</span><span class="fit">FIT</span></div><div></div></div><h1>Settings</h1><div class="subtitle">Control your ShiftFit app, data and preferences.</div><div class="group"><h3>APP PREFERENCES</h3><button class="item" data-page="notifications"><span class="icon">🔔</span><span><span class="title">Notifications</span><span class="copy">Manage your reminders and alerts</span><span class="value">${v.notifications?"Enabled":"Disabled"}</span></span><span class="arrow">›</span></button><button class="item" data-page="appearance"><span class="icon">🎨</span><span><span class="title">Appearance</span><span class="copy">Theme and display options</span><span class="value">${v.appearance==="light"?"Light":"Dark"}</span></span><span class="arrow">›</span></button><button class="item" data-page="app"><span class="icon">⚙️</span><span><span class="title">App settings</span><span class="copy">Units and week preferences</span><span class="value">${v.units==="imperial"?"Imperial":"Metric"}</span></span><span class="arrow">›</span></button></div><div class="group"><h3>DATA & ACCOUNT</h3><button class="item" data-page="privacy"><span class="icon">🛡️</span><span><span class="title">Data & Privacy</span><span class="copy">Export or clear your local ShiftFit data</span></span><span class="arrow">›</span></button><button class="item" data-page="account"><span class="icon">☁️</span><span><span class="title">Account & Sync</span><span class="copy">Account and cloud synchronisation</span><span class="value">Local device</span></span><span class="arrow">›</span></button></div><div class="group"><h3>SUPPORT & LEGAL</h3><button class="item" data-page="support"><span class="icon">❓</span><span><span class="title">Help & Support</span><span class="copy">Get help using ShiftFit</span></span><span class="arrow">›</span></button><button class="item" data-page="about"><span class="icon">ℹ️</span><span><span class="title">About ShiftFit</span><span class="copy">Version and product information</span></span><span class="arrow">›</span></button><button class="item" data-page="terms"><span class="icon">📜</span><span><span class="title">Terms & Conditions</span><span class="copy">Rules for using ShiftFit</span></span><span class="arrow">›</span></button><button class="item" data-page="privacy-policy"><span class="icon">🔒</span><span><span class="title">Privacy Policy</span><span class="copy">How ShiftFit handles information</span></span><span class="arrow">›</span></button></div></div>`;m.classList.add("open");m.querySelector(".back").onclick=close;m.onclick=e=>{if(e.target===m)close();};m.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>renderPage(b.dataset.page));}
  function renderPage(page){if(page==="notifications")return notifications();if(page==="appearance")return appearance();if(page==="app")return appSettings();if(page==="privacy")return privacy();if(page==="account")return account();if(page==="support")return support();if(page==="about")return about();if(page==="terms")return terms();if(page==="privacy-policy")return privacyPolicy();}
  function notifications(){const v=settings();const m=shell("Notifications","Choose which ShiftFit reminders you want to receive on this device.",`<div class="group"><label class="check"><input type="checkbox" data-k="notifications" ${v.notifications?"checked":""}> Enable notifications</label><label class="check"><input type="checkbox" data-k="mealReminders" ${v.mealReminders?"checked":""}> Meal reminders</label><label class="check"><input type="checkbox" data-k="workoutReminders" ${v.workoutReminders?"checked":""}> Workout reminders</label><label class="check"><input type="checkbox" data-k="waterReminders" ${v.waterReminders?"checked":""}> Water reminders</label><button class="save" data-save>Save notification settings</button><div class="note">These preferences are stored now. Push notification delivery will be connected when ShiftFit adds its notification service.</div></div>`);m.querySelector("[data-save]").onclick=()=>{const n=settings();m.querySelectorAll("[data-k]").forEach(x=>n[x.dataset.k]=x.checked);saveSettings(n);renderHome();toast("Notification settings saved");};}
  function appearance(){const v=settings();const m=shell("Appearance","Choose how ShiftFit should display itself on this device.",`<div class="group"><label class="label">Theme</label><select class="field" data-k="appearance"><option value="dark">Dark</option><option value="light">Light</option><option value="system">Use device setting</option></select><button class="save" data-save>Save appearance</button><div class="note">The setting is saved centrally so future ShiftFit screens can follow the same preference.</div></div>`);m.querySelector("[data-k]").value=v.appearance;m.querySelector("[data-save]").onclick=()=>{const n=settings();n.appearance=m.querySelector("[data-k]").value;saveSettings(n);renderHome();toast("Appearance saved");};}
  function appSettings(){const v=settings();const m=shell("App settings","Set the basic preferences used across ShiftFit.",`<div class="group"><label class="label">Units</label><select class="field" data-k="units"><option value="metric">Metric (kg, cm)</option><option value="imperial">Imperial (lb, ft/in)</option></select><label class="label">Week starts on</label><select class="field" data-k="weekStarts"><option value="monday">Monday</option><option value="sunday">Sunday</option></select><button class="save" data-save>Save app settings</button></div>`);m.querySelector('[data-k="units"]').value=v.units;m.querySelector('[data-k="weekStarts"]').value=v.weekStarts;m.querySelector("[data-save]").onclick=()=>{const n=settings();n.units=m.querySelector('[data-k="units"]').value;n.weekStarts=m.querySelector('[data-k="weekStarts"]').value;saveSettings(n);renderHome();toast("App settings saved");};}
  function privacy(){const m=shell("Data & Privacy","Your current ShiftFit data is stored locally on this device.",`<div class="group"><h3>YOUR DATA</h3><div class="legal">ShiftFit stores profile, plan, meal, workout, weight, progress and preference data locally so the app can work on this device.</div><button class="save" data-export>Export my data</button><button class="secondary danger" data-clear>Clear all local ShiftFit data</button><div class="note">Clear is permanent for data stored locally by ShiftFit. It does not delete anything from an external account or service.</div></div>`);m.querySelector("[data-export]").onclick=()=>{const data={exportedAt:new Date().toISOString(),settings:raw(STORE,{}),localStorage:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&(/shiftfit|weeklyMeals|mealPreferences|shoppingItems|selectedShift|customShift/i.test(k)))data.localStorage[k]=raw(k,localStorage.getItem(k));}const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="shiftfit-data.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("Your ShiftFit data export is ready");};m.querySelector("[data-clear]").onclick=()=>{if(!confirm("Clear all local ShiftFit data? This cannot be undone."))return;const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&(/shiftfit|weeklyMeals|mealPreferences|shoppingItems|selectedShift|customShift/i.test(k)))keys.push(k);}keys.forEach(k=>localStorage.removeItem(k));toast("Local ShiftFit data cleared");setTimeout(renderHome,500);};}
  function account(){shell("Account & Sync","ShiftFit is currently device-first. Cloud accounts can be added without changing your local data model.",`<div class="group"><h3>CURRENT STATUS</h3><div class="legal"><strong>Local device storage</strong><br>Everything you have created in ShiftFit is currently stored on this device.</div><button class="secondary" type="button" disabled>Sign in / create account — coming next</button><div class="note">When accounts are introduced, this area will handle sign-in, backup and synchronisation. No account is required for the current app.</div></div>`);}
  function support(){shell("Help & Support","Quick answers for using ShiftFit.",`<div class="group"><h3>COMMON TASKS</h3><div class="legal"><strong>Change your goal</strong><br>Profile → Goal & Nutrition → choose your goal → Save & Generate My Plan.<h2>Meals not updating?</h2>Run Save & Generate My Plan again so the current targets are used to rebuild your week.<h2>Need help?</h2>For now, use the in-app settings and profile controls. A direct support contact form can be connected here later.</div></div>`);}
  function about(){shell("About ShiftFit","Built to help people manage fitness, nutrition and routines around real life and shift work.",`<div class="group"><div class="legal"><strong>ShiftFit</strong><br>Personal fitness, nutrition and shift-planning companion.<h2>Version</h2>Settings v2 · Profile Control Centre · Goal-aware meal planning<h2>What ShiftFit does</h2>Personalises targets, builds weekly meals, tracks workouts, weight and progress, and is designed around changing shift schedules.</div></div>`);}
  function terms(){shell("Terms & Conditions","General terms for using the current ShiftFit application.",`<div class="group legal"><p>ShiftFit is provided as a fitness and nutrition planning tool. Information and recommendations are intended for general wellbeing and are not medical advice.</p><h2>Use of the app</h2><p>You are responsible for the information you enter and for deciding whether an activity, food choice or target is appropriate for you.</p><h2>Accuracy</h2><p>Targets, meal plans and estimates may not be exact. Check important nutrition, allergy and health requirements independently.</p><h2>Changes</h2><p>ShiftFit may change features, calculations and content as the product develops.</p></div>`);}
  function privacyPolicy(){shell("Privacy Policy","A simple explanation of how the current device-first version handles data.",`<div class="group legal"><h2>Local storage</h2><p>The current app stores your ShiftFit information locally on your device so features can work without an online account.</p><h2>What is stored</h2><p>This can include profile details, nutrition targets, meal plans, workout logs, weight and progress history, and app preferences.</p><h2>Sharing</h2><p>The current device-first storage model does not require a ShiftFit cloud account. Future online services will have their own privacy controls and documentation.</p><h2>Your controls</h2><p>You can use Data & Privacy to export or clear locally stored ShiftFit data.</p></div>`);}
  function modal(){if(document.getElementById(MODAL))return;const m=document.createElement("div");m.id=MODAL;document.body.appendChild(m);}
  function bind(){document.querySelectorAll(".profile-btn").forEach(function(btn){if(btn.dataset.shiftfitSettingsBound==="2")return;btn.dataset.shiftfitSettingsBound="2";btn.addEventListener("click",function(e){e.preventDefault();e.stopImmediatePropagation();renderHome();},true);});}
  function boot(){styles();applySettings(settings());modal();bind();[300,800,1500,2500].forEach(t=>setTimeout(bind,t));}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();