/* ShiftFit Account & Sync — Supabase email/password authentication. */
(function(){
  "use strict";
  if(window.__shiftFitAuthLoaded)return;
  window.__shiftFitAuthLoaded=true;
  var CLIENT=null;var CONFIG=null;var ready=null;var SUPABASE_CDN="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";
  function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");}
  function loadScript(src){return new Promise(function(resolve,reject){var s=document.createElement("script");s.src=src;s.async=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
  async function init(){var response=await fetch("/api/config",{cache:"no-store"});CONFIG=await response.json();if(!CONFIG.supabaseUrl||!CONFIG.supabasePublishableKey)return null;if(!window.supabase||!window.supabase.createClient)await loadScript(SUPABASE_CDN);CLIENT=window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});CLIENT.auth.onAuthStateChange(function(event,session){window.dispatchEvent(new CustomEvent("shiftfitAuthChanged",{detail:{event:event,session:session,user:session&&session.user||null}}));});return CLIENT;}
  ready=init().catch(function(error){console.warn("ShiftFit auth is not configured yet.",error);return null;});
  async function getClient(){return ready;} async function session(){var c=await getClient();if(!c)return null;var r=await c.auth.getSession();return r.data&&r.data.session||null;}
  async function signInWithPassword(email,password){var c=await getClient();if(!c)throw new Error("ShiftFit account services are not configured yet.");var r=await c.auth.signInWithPassword({email:email,password:password});if(r.error)throw r.error;return r.data;}
  async function signUp(email,password,name){var c=await getClient();if(!c)throw new Error("ShiftFit account services are not configured yet.");var r=await c.auth.signUp({email:email,password:password,options:{data:{full_name:name||""},emailRedirectTo:window.location.origin}});if(r.error)throw r.error;return r.data;}
  async function resetPassword(email){var c=await getClient();if(!c)throw new Error("ShiftFit account services are not configured yet.");var r=await c.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(r.error)throw r.error;}
  async function signOut(){var c=await getClient();if(!c)return;var r=await c.auth.signOut();if(r.error)throw r.error;}
  async function deleteAccount(){throw new Error("Account deletion requires the secure server-side deletion endpoint and is not enabled yet.");}
  function localSnapshot(){var data={};for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&(/shiftfit|weeklyMeals|mealPreferences|shoppingItems|selectedShift|customShift/i.test(k))){try{data[k]=JSON.parse(localStorage.getItem(k));}catch(_){data[k]=localStorage.getItem(k);}}}return data;}
  function closeAccountToSettings(){var m=document.getElementById("shiftfit-settings-split-modal");if(m)m.classList.remove("open");}
  function accountShell(){var m=document.getElementById("shiftfit-settings-split-modal");if(!m)return null;var sheet=m.querySelector(".sheet");if(!sheet)return null;sheet.innerHTML='<div class="top"><button class="back" type="button" data-shiftfit-account-back aria-label="Back">‹</button><div class="logo"><span class="bolt">⚡</span><span>SHIFT</span><span class="fit">FIT</span></div><div></div></div><div class="backrow"><h1>Account & Sync</h1></div><div class="subtitle">Create your permanent ShiftFit account and keep your data secure.</div><div id="shiftfit-account-state"></div>';sheet.querySelector(".back").onclick=function(event){event.preventDefault();event.stopPropagation();closeAccountToSettings();};return sheet;}
  function renderMessage(box,text,type){box.innerHTML='<div class="legal" style="margin-top:12px;'+(type==="error"?'color:#ff8f8f;':'')+'">'+esc(text)+'</div>';}
  async function paintAccount(){var box=document.getElementById("shiftfit-account-state");if(!box)return;box.innerHTML='<div class="group"><h3>ACCOUNT</h3><div class="legal">Checking your ShiftFit account…</div></div>';var c=await getClient();if(!c){box.innerHTML='<div class="group"><h3>ACCOUNT SERVICES</h3><div class="legal"><strong>Almost ready.</strong><br>ShiftFit is prepared for secure email/password accounts, but the Supabase connection still needs its runtime URL and publishable key.</div><div class="note">No temporary or fake account is being created.</div></div>';return;}var s=await session();if(!s){renderSignedOut(box);return;}var u=s.user||{};var meta=u.user_metadata||{};var name=meta.full_name||meta.name||u.email||"ShiftFit member";box.innerHTML='<div class="group"><h3>SIGNED IN</h3><div style="display:flex;align-items:center;gap:12px"><div style="width:52px;height:52px;border-radius:50%;overflow:hidden;border:1px solid #39466f;background:#11182d;display:grid;place-items:center;font-size:22px">👤</div><div><strong>'+esc(name)+'</strong><div class="note" style="margin-top:3px">'+esc(u.email||"")+'</div></div></div><div class="legal" style="margin-top:16px"><strong>Account status:</strong> Active<br><strong>Authentication:</strong> Email & password<br><strong>Data:</strong> Cloud backup enabled</div><button class="save" id="shiftfit-sync-now" type="button">Sync my ShiftFit data</button><button class="secondary" id="shiftfit-signout" type="button">Sign out</button><div class="note">Your ShiftFit data can now be backed up to your account and restored on another device.</div></div>';document.getElementById("shiftfit-sync-now").onclick=async function(){var b=this;b.disabled=true;b.textContent="Syncing…";try{if(window.shiftfitCloudSync&&typeof window.shiftfitCloudSync.sync==="function")await window.shiftfitCloudSync.sync();else toast("Cloud sync is still loading. Please try again.");}finally{b.disabled=false;b.textContent="Sync my ShiftFit data";}};document.getElementById("shiftfit-signout").onclick=async function(){try{await signOut();paintAccount();}catch(e){alert(e.message||"Sign out failed.");}};}
  function renderSignedOut(box){box.innerHTML='<div class="group"><h3>SIGN IN</h3><label class="note" for="shiftfit-login-email">Email</label><input id="shiftfit-login-email" type="email" autocomplete="email" placeholder="you@example.com" style="width:100%;margin-top:6px"><label class="note" for="shiftfit-login-password" style="display:block;margin-top:14px">Password</label><input id="shiftfit-login-password" type="password" autocomplete="current-password" placeholder="Your password" style="width:100%;margin-top:6px"><button class="save" id="shiftfit-login" type="button">Sign in</button><button class="secondary" id="shiftfit-show-signup" type="button">Create account</button><button class="secondary" id="shiftfit-forgot" type="button">Forgot password?</button><div id="shiftfit-auth-message"></div></div>';document.getElementById("shiftfit-login").onclick=async function(){var email=document.getElementById("shiftfit-login-email").value.trim();var password=document.getElementById("shiftfit-login-password").value;if(!email||!password){renderMessage(document.getElementById("shiftfit-auth-message"),"Enter your email and password.","error");return;}this.disabled=true;this.textContent="Signing in…";try{await signInWithPassword(email,password);paintAccount();}catch(e){this.disabled=false;this.textContent="Sign in";renderMessage(document.getElementById("shiftfit-auth-message"),e.message||"Sign in failed.","error");}};document.getElementById("shiftfit-show-signup").onclick=function(){renderSignup(box);};document.getElementById("shiftfit-forgot").onclick=function(){renderForgot(box);};}
  function renderSignup(box){box.innerHTML='<div class="group"><h3>CREATE ACCOUNT</h3><label class="note" for="shiftfit-signup-name">Name</label><input id="shiftfit-signup-name" type="text" autocomplete="name" placeholder="Your name" style="width:100%;margin-top:6px"><label class="note" for="shiftfit-signup-email">Email</label><input id="shiftfit-signup-email" type="email" autocomplete="email" placeholder="you@example.com" style="width:100%;margin-top:6px"><label class="note" for="shiftfit-signup-password">Password</label><input id="shiftfit-signup-password" type="password" autocomplete="new-password" placeholder="At least 8 characters" style="width:100%;margin-top:6px"><button class="save" id="shiftfit-signup" type="button">Create my ShiftFit account</button><button class="secondary" id="shiftfit-back-login" type="button">Back to sign in</button><div id="shiftfit-auth-message"></div></div>';document.getElementById("shiftfit-signup").onclick=async function(){var name=document.getElementById("shiftfit-signup-name").value.trim();var email=document.getElementById("shiftfit-signup-email").value.trim();var password=document.getElementById("shiftfit-signup-password").value;if(!email||!password){renderMessage(document.getElementById("shiftfit-auth-message"),"Enter an email and password.","error");return;}if(password.length<8){renderMessage(document.getElementById("shiftfit-auth-message"),"Use a password with at least 8 characters.","error");return;}this.disabled=true;this.textContent="Creating account…";try{var data=await signUp(email,password,name);if(data.session){paintAccount();setTimeout(function(){if(window.shiftfitCloudSync&&typeof window.shiftfitCloudSync.sync==="function")window.shiftfitCloudSync.sync();},500);}else{renderMessage(document.getElementById("shiftfit-auth-message"),"Account created. Check your email to confirm your account, then sign in.");this.disabled=false;this.textContent="Create my ShiftFit account";}}catch(e){this.disabled=false;this.textContent="Create my ShiftFit account";renderMessage(document.getElementById("shiftfit-auth-message"),e.message||"Account creation failed.","error");}};document.getElementById("shiftfit-back-login").onclick=function(){renderSignedOut(box);};}
  function renderForgot(box){box.innerHTML='<div class="group"><h3>RESET PASSWORD</h3><div class="legal">Enter your account email and ShiftFit will send a password reset link.</div><label class="note" for="shiftfit-reset-email">Email</label><input id="shiftfit-reset-email" type="email" autocomplete="email" placeholder="you@example.com" style="width:100%;margin-top:6px"><button class="save" id="shiftfit-reset" type="button">Send reset link</button><button class="secondary" id="shiftfit-back-login" type="button">Back to sign in</button><div id="shiftfit-auth-message"></div></div>';document.getElementById("shiftfit-reset").onclick=async function(){var email=document.getElementById("shiftfit-reset-email").value.trim();if(!email){renderMessage(document.getElementById("shiftfit-auth-message"),"Enter your email.","error");return;}this.disabled=true;this.textContent="Sending…";try{await resetPassword(email);renderMessage(document.getElementById("shiftfit-auth-message"),"If that email has a ShiftFit account, a password reset link has been sent.");}catch(e){this.disabled=false;this.textContent="Send reset link";renderMessage(document.getElementById("shiftfit-auth-message"),e.message||"Could not send reset link.","error");}};document.getElementById("shiftfit-back-login").onclick=function(){renderSignedOut(box);};}
  function renderAccount(){accountShell();paintAccount();}
  function openSignup(){
    var old=document.getElementById("shiftfit-signup-modal");
    if(old)old.remove();
    var style=document.getElementById("shiftfit-signup-modal-style");
    if(!style){style=document.createElement("style");style.id="shiftfit-signup-modal-style";style.textContent="#shiftfit-signup-modal{position:fixed;inset:0;z-index:100050;display:flex;align-items:center;justify-content:center;padding:22px;background:rgba(0,0,0,.72)}#shiftfit-signup-modal .card{width:min(460px,100%);max-height:calc(100dvh - 44px);overflow:auto;background:#11162b;border:1px solid #303a60;border-radius:22px;box-shadow:0 24px 80px rgba(0,0,0,.55);padding:22px}#shiftfit-signup-modal .title{font-size:24px;font-weight:900;margin:0 0 6px}#shiftfit-signup-modal .sub{color:#aab1c5;font-size:14px;margin-bottom:18px}#shiftfit-signup-modal label{display:block;color:#aab1c5;font-size:12px;font-weight:800;margin:12px 0 6px}#shiftfit-signup-modal input{width:100%;height:48px;border-radius:12px;border:1px solid #303a60;background:#080b18;color:#fff;padding:0 13px;font-size:16px}#shiftfit-signup-modal button{width:100%;height:48px;border-radius:12px;border:0;margin-top:14px;font-weight:900;font-size:14px}#shiftfit-signup-modal .primary{background:#6d28d9;color:#fff}#shiftfit-signup-modal .secondary{background:#1b223a;color:#fff;border:1px solid #303a60}#shiftfit-signup-modal .close{background:transparent;color:#aab1c5;margin-top:8px}#shiftfit-signup-modal .msg{margin-top:12px;font-size:13px;color:#aab1c5}#shiftfit-signup-modal .error{color:#ff8f8f}";document.head.appendChild(style);}
    var m=document.createElement("div");m.id="shiftfit-signup-modal";m.innerHTML='<div class="card"><h2 class="title">Create your ShiftFit account</h2><div class="sub">Save your progress and keep your personalised data across devices.</div><label for="sf-name">Name</label><input id="sf-name" autocomplete="name" placeholder="Your name"><label for="sf-email">Email</label><input id="sf-email" type="email" autocomplete="email" placeholder="you@example.com"><label for="sf-password">Password</label><input id="sf-password" type="password" autocomplete="new-password" placeholder="At least 8 characters"><button class="primary" id="sf-create">Create account</button><button class="secondary" id="sf-login">I already have an account</button><button class="close" id="sf-close">Back</button><div id="sf-msg" class="msg"></div></div>';
    document.body.appendChild(m);
    m.querySelector("#sf-close").onclick=function(){m.remove();};
    m.querySelector("#sf-login").onclick=function(){m.remove();var modal=document.getElementById("shiftfit-settings-split-modal");if(modal)modal.classList.add("open");renderAccount();};
    m.querySelector("#sf-create").onclick=async function(){var name=m.querySelector("#sf-name").value.trim();var email=m.querySelector("#sf-email").value.trim();var password=m.querySelector("#sf-password").value;var msg=m.querySelector("#sf-msg");if(!email||!password){msg.className="msg error";msg.textContent="Enter your email and password.";return;}if(password.length<8){msg.className="msg error";msg.textContent="Use a password with at least 8 characters.";return;}this.disabled=true;this.textContent="Creating account…";try{var data=await signUp(email,password,name);if(data.session){msg.className="msg";msg.textContent="Account created. Your ShiftFit data is now linked.";setTimeout(function(){m.remove();if(window.shiftfitCloudSync&&typeof window.shiftfitCloudSync.sync==="function")window.shiftfitCloudSync.sync();},700);}else{msg.className="msg";msg.textContent="Account created. Check your email to confirm, then sign in.";this.disabled=false;this.textContent="Create account";}}catch(e){this.disabled=false;this.textContent="Create account";msg.className="msg error";msg.textContent=e.message||"Account creation failed.";}};
  }
  function toast(text){var old=document.querySelector(".toast");if(old)old.remove();var t=document.createElement("div");t.className="toast";t.textContent=text;document.body.appendChild(t);setTimeout(function(){t.remove();},2400);}
  window.shiftfitAuth={ready:ready,getClient:getClient,getSession:session,signInWithPassword:signInWithPassword,signUp:signUp,resetPassword:resetPassword,signOut:signOut,deleteAccount:deleteAccount,localSnapshot:localSnapshot,renderAccount:renderAccount,openSignup:openSignup};
  document.addEventListener("click",function(e){var button=e.target&&e.target.closest?e.target.closest('[data-page="account"]'):null;if(!button)return;e.preventDefault();e.stopImmediatePropagation();var m=document.getElementById("shiftfit-settings-split-modal");if(m)m.classList.add("open");renderAccount();},true);
  window.addEventListener("shiftfitAuthChanged",function(){if(document.getElementById("shiftfit-account-state"))paintAccount();});
})();
